### ISSUE TITLE
Resource returning empty response causes build log to keep 'loading'

### ISSUE THREAD

**Issue by aequitas** [concourse/atc#51]
When a 'out' resource returns an empty object `{}` the currently open view of the build status renders it just fine. But after reloading the build view the build status overview just shows a bar with 'loading' and a spinner.

javascript console throws this erorr: 

    failed to fetch plan: UnexpectedPayload ("expecting an object but got null"): ({ build = { id = 106, name = "35", job = Just { name = "build", pipelineName = "pylib" }, status = Succeeded, duration = { startedAt = Just {}, finishedAt = Just {} } }, steps = Nothing, errors = Nothing, state = StepsLoading, context = { events = Address <function>, buildStatus = Address <function> }, eventSource = Nothing, eventSourceOpened = False },None)

When the resource returns an object with empty 'version' `{"version": {}}` this problem does not happen.

**Comment by xoebus** [comment]
Yeah, an *out* action must always return a version. The first thing that notices that this is missing in this case is when we try and parse the output in UI. This isn't great and it would be nicer if `atc` checked for this and errored when it was processing the output.

I'm going to close this though because we're unlikely to look at this soon but I'd probably merge a PR that fixed this.
