### ISSUE TITLE
0.73.0 Font downloads broken in Safari

### ISSUE THREAD

**Issue by nebhale** [concourse/atc#52]
The `0.73.0` release has broken font downloads for Safari only.  You can see the behavior on https://java-experience.ci.springapps.io/pipelines/cf-java-client.  It appears that 404's are being returned for the font artifacts:

![screen shot 2016-02-18 at 11 19 14](https://cloud.githubusercontent.com/assets/60754/13155241/b3820940-d631-11e5-9a1e-73e1764c29e0.png)

The downloads appear to work properly in Chrome.

**Comment by xoebus** [comment]
Thanks for reporting.

Safari is making requests to `https://ci.concourse.ci/public/fonts/gc/fontawesome-webfont.ttf?v=4.5.0` instead of `https://ci.concourse.ci/public/fonts/fontawesome-webfont.ttf?v=4.5.0`. I can see where in the code that this mistake is but I have no idea why it's different in Chrome.

I'll prioritize this for the next release and continue screaming curses at web development.
