### ISSUE TITLE
Moar information on unexpected response code of: 500

### ISSUE THREAD

**Issue by clayrichardson** [concourse/atc#75]
Moar information should be given instead of the cryptic message.

![pasted image at 2016_04_18 12_24 pm](https://cloud.githubusercontent.com/assets/883079/14619464/8a5c7284-056c-11e6-9cf4-5a4f00a35c7c.png)

**Comment by clayrichardson** [comment]
The workers had run out of disk real estate.

**Comment by vito** [comment]
Not a whole lot we can do about these messages ourselves; we're just bubbling up error messages. This kind of issue isn't very actionable without logs and such tracing to the component that it ultimately came from (perhaps Garden in this case).

Regardless, things have changed quite a bit since this was opened (we use an entirely different Garden backend), so I doubt there's much change we can do.
